apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: mailbot-healthcheck
  namespace: hyly-prod
spec:
  default:
    checkIntervalSec: 300
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 5000
        requestPath: "/heartbeat"
    healthyThreshold: 1
    healthyThreshold: 1
    timeoutSec: 60
    unhealthyThreshold: 3
  targetRef:
    group: ""
    kind: Service
    name: mailbot
