apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: chatcdp-services-healthcheck
  namespace: hyly-prod
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 5000
        requestPath: "/heartbeat"
  targetRef:
    group: ""
    kind: Service
    name: chatcdp-services