apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyly-subject-detector-pvc
  namespace: hyly-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo