version: '3.9'
services:
    # MySQL Database
    mysql_db_prod: 
      image: mysql:8.0
      restart: always
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      ports:
          - "3306:3306"
      volumes:
          - ./volumes/mysql_data:/var/lib/mysql
      command: --max-allowed-packet=128M
    
    # MongoDB Database
    mongo_db_prod:
      image: mongo:5.0
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - ./volumes/mongo_data:/data/db
      depends_on:
          - mysql_db
      
    chatcdp_prod: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/chat-cdp/chatcdp:latest
      ports:
        - "5000:5000"
      command: "flask run --host=0.0.0.0 --port=5000"
      volumes: 
          - ./volumes/chatCDP_data:/app

    # All services  
    # pai_datascience_services_prod: 
    #     build: .
    #     volumes: 
    #         - ./:/app
    #     ports: 
    #         - "80:80"
    #     depends_on:
    #         - mysql_db
    #         - mongo_db

volumes:
  mysql_data:
    external: true
  mongo_data:
    external: true
    
networks:
  default:
    name: microservices
    external: true