apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-hayleygpt
  namespace: hyly-prod
data:
  DB_NAME: hyly_ai_mailgpt
  DB_NAME_QA: hyly_ai_mailgpt_qa
  PINECONE_ENV: us-east4-gcp
  ENVIRONMENT: prod
  PYTHONPATH: /app/MLOps/Loggers
  REDIS_URL_Prod: redis://10.18.171.123:6379