apiVersion: apps/v1
kind: Deployment
metadata:
  name: pai_datascience_services
  namespace: hyly-prod
  labels:
    app: pai_datascience_services
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: pai_datascience_services

  template:
    metadata:
      name: pai_datascience_services
      labels:
        app: pai_datascience_services
    spec:
      restartPolicy: Always

      # imagePullSecrets:
      #   - name: myhyly-ecr-secret

      containers:
        - name: pai_datascience_services
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/pai-datascience-services:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 80
            failureThreshold: 30
            periodSeconds: 10