apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl_hub
  namespace: hyly-prod
  labels:
    app: etl_hub
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: etl_hub

  template:
    metadata:
      name: etl_hub
      labels:
        app: etl_hub
    spec:
      restartPolicy: Always

      # imagePullSecrets:
      #   - name:

      containers:
        - name: etl_hub
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/etl-hub:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 3000
            failureThreshold: 30
            periodSeconds: 10