apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayleygpt
  namespace: hyly-prod
  labels:
    app: hayleygpt
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

  selector:
    matchLabels:
      app: hayleygpt

  template:
    metadata:
      name: hayleygpt
      labels:
        app: hayleygpt
    spec:
      restartPolicy: Always

      # imagePullSecrets:
      #   - name:

      containers:
        - name: hayleygpt
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/hayleygpt:latest
          imagePullPolicy: Always

          envFrom:
          - configMapRef:
              name: configmap-hayleygpt
          - secretRef:
              name: secret-hayleygpt

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            failureThreshold: 30
            periodSeconds: 10