apiVersion: apps/v1
kind: Deployment
metadata:
  name: hayleygpt
  namespace: hyly-prod
  labels:
    app: hayleygpt
spec:
  replicas: 3
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

  selector:
    matchLabels:
      app: hayleygpt

  template:
    metadata:
      name: hayleygpt
      labels:
        app: hayleygpt
    spec:
      restartPolicy: Always
      # imagePullSecrets:
      #   - name:

      volumes:
        - name: secret-hayleygpt
          secret:
            secretName: secret-hayleygpt
            items:
              - key: signals-keyfile.json
                path: signals-keyfile.json
        - name: hyly-subject-detector-pvc-vol
          persistentVolumeClaim:
            claimName: hyly-subject-detector-pvc
          

      containers:
        - name: hayleygpt
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/hayleygpt:latest
          imagePullPolicy: Always

          envFrom:
          - configMapRef:
              name: configmap-hayleygpt
          - secretRef:
              name: secret-hayleygpt

          volumeMounts:
            - name: secret-hayleygpt
              mountPath: "/app/config/signals-keyfile.json"
              subPath: signals-keyfile.json
              readOnly: true
              
            - mountPath: /model/hyly-subject-detector/
              name: hyly-subject-detector-pvc-vol

          lifecycle:
           postStart:
            exec:
             command:
               - "/bin/sh"
               - "-c"
               - "echo '3.86.63.232 db-prod1.hy.ly' >> /etc/hosts; echo '44.210.143.44 db-prod2.hy.ly' >> /etc/hosts; echo '3.95.168.139 db-prod3.hy.ly' >> /etc/hosts"

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "6000Mi"
              cpu: "800m"
            # limits:
            #   memory: "1024Mi"
            #   cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            failureThreshold: 30
            periodSeconds: 10
