apiVersion: apps/v1
kind: Deployment
metadata:
  name: hylyimageclassification
  namespace: hyly-prod
  labels:
    app: hylyimageclassification
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

  selector:
    matchLabels:
      app: hylyimageclassification

  template:
    metadata:
      name: hylyimageclassification
      labels:
        app: hylyimageclassification
    spec:
      restartPolicy: Always

      volumes:
        - name: hyly-subject-detector-pvc-vol
          persistentVolumeClaim:
            claimName: hyly-subject-detector-pvc
         
      # initContainers:
      #   - name: copy-model
      #     image: google/cloud-sdk
      #     command: ["gsutil", "-m", "cp", "-r", "gs://hyly-subject-detector-model/hayley_subject_detector", "/model/hyly-subject-detector/"]
      #     volumeMounts:
      #       - mountPath: /model/hyly-subject-detector/
      #         name: hyly-subject-detector-pvc-vol

      containers:
        - name: hylyimageclassification
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/hylyimageclassification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          volumeMounts:
            - mountPath: /model/hyly-subject-detector/
              name: hyly-subject-detector-pvc-vol

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            failureThreshold: 30
            periodSeconds: 10