apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-hub
  namespace: hyly-prod
  labels:
    app: etl-hub
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: etl-hub

  template:
    metadata:
      name: etl-hub
      labels:
        app: etl-hub
    spec:
      restartPolicy: Always

      # imagePullSecrets:
      #   - name:

      containers:
        - name: etl-hub
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/etl-hub:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"