apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcdp-services
  namespace: hyly-prod
  labels:
    app: chatcdp-services
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: chatcdp-services

  template:
    metadata:
      name: chatcdp-services
      labels:
        app: chatcdp-services
    spec:
      restartPolicy: Always

      # imagePullSecrets:
      #   - name:

      containers:
        - name: chatcdp-services
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/chatcdp-services:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: secret-chatcdp-services

          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            failureThreshold: 30
            periodSeconds: 10