apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcdp
  namespace: hyly-prod
  labels:
    app: chatcdp
spec:
  replicas: 1
  minReadySeconds: 10
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5

  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0

  selector:
    matchLabels:
      app: chatcdp

  template:
    metadata:
      name: chatcdp
      labels:
        app: chatcdp
    spec:
      restartPolicy: Always
      volumes:
        - name: hyly-subject-detector-pvc-vol
          persistentVolumeClaim:
            claimName: hyly-subject-detector-pvc

      # imagePullSecrets:
      #   - name:

      containers:
        - name: chatcdp
          image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-prod/chatcdp:latest
          imagePullPolicy: Always

          envFrom:
          - configMapRef:
              name: configmap-chatcdp
          - secretRef:
              name: secret-chatcdp

          ports:
            - containerPort: 5000

          volumeMounts:
            - mountPath: /model/hyly-subject-detector/
              name: hyly-subject-detector-pvc-vol

          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"

          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          startupProbe:
            httpGet:
              path: /heartbeat
              port: 5000
            failureThreshold: 30
            periodSeconds: 10