apiVersion: v1
kind: Service
metadata:
  name: chatcdp
  namespace: hyly-prod
spec:
  type: ClusterIP
  selector:
    app: chatcdp
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
