apiVersion: v1
kind: Service
metadata:
  name: chatcdp-services
  namespace: hyly-prod
spec:
  type: NodePort
  selector:
    app: chatcdp-services
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5000
