apiVersion: v1
kind: Service
metadata:
  name: hylyimageclassification
  namespace: hyly-prod
spec:
  type: NodePort
  selector:
    app: hylyimageclassification
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
