apiVersion: v1
kind: Service
metadata:
  name: oneminutechatbot
  namespace: hyly-prod
spec:
  type: NodePort
  selector:
    app: oneminutechatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
