version: '3.4'
services:
    # chatCDP services https://github.com/munishgandhi/PAI.APP.ChatCDP
    chatcdp_services_staging: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/chatcdp-services:latest
      env_file:
        - /home/ubuntu/code/.env.chatcdp_services_stg
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.50'
            memory: 5g
      ports:
        - "5011:5000"
      volumes:
        - /home/ubuntu/code/.signals-keyfile.json:/app/config/signals-keyfile.json
        - /home/ubuntu/code/hayley_subject_detector/hayley_subject_detector:/app/models/hayley_subject_detector

    # Hayleygpt https://github.com/munishgandhi/JAI.APP.HayleyChatBot
    hayleygpt_staging: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/hayleygpt:latest
      env_file:
        - /home/ubuntu/code/.env.hayleygpt_stg
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports: 
        - "5006:5000"
      volumes:
        - /home/ubuntu/code/.signals-keyfile.json:/app/config/signals-keyfile.json
        - /home/ubuntu/code/hayley_subject_detector/hayley_subject_detector:/app/models/hayley_subject_detector
  

    # PAI datascience https://github.com/munishgandhi/etl-hub/tree/datascience_stg
    pai_datascience_services_staging: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/pai-datascience-services:latest
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports: 
        - "82:80"
  
    # mailBot https://github.com/munishgandhi/JAI.APP.HayleyMailBot
    mailBot_stg:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/mailbot:latest
      env_file:
        - /home/ubuntu/code/.env.mailBot_stg
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports:
        - "5016:5000"
      volumes:
        - /home/ubuntu/code/hayley_subject_detector/hayley_subject_detector:/app/models/hayley_subject_detector

    # hayleyImageClassification https://github.com/munishgandhi/Hayley.JAI.Image.Classification.git
    hylyimageclassification_stg:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/hylyimageclassification:latest
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.50'
            memory: 5g
      ports:
        - "5041:5000"
        
    # Oneminutechatbot https://github.com/munishgandhi/one-minute-chatbot
    oneminutechatbot_staging::
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/oneminutechatbot:latest 
      env_file:
        - /home/ubuntu/code/.env.oneminutechatbot_stg
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports:
        - "8001:8000"

networks:
  default:
    name: microservices_staging
    external: true
