version: '3.4'
services:
    # MySQL Database
    mysql_db_staging: 
      image: mysql:8.0
      restart: always
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: true
      ports:
        - "3316:3306"
      volumes:
        - /db_volumes/mysql_data_staging:/var/lib/mysql
    
    # MongoDB Database
    mongo_db_staging:
      image: mongo:5.0
      restart: always
      ports:
        - "27027:27017"
      volumes:
        - /db_volumes/mongo_data_staging:/data/db
      depends_on:
        - mysql_db_staging

    # Redis Database
    redis_db_staging:
      image: redis:latest
      restart: always
      ports:
        - "6389:6379"
      volumes:
        - /db_volumes/redis_data_staging:/data
      command: redis-server --bind 0.0.0.0
      depends_on:
        - mysql_db_staging
        - mongo_db_staging
    
    # chatCDP https://github.com/munishgandhi/chatCDP 
    chatcdp_staging: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/chatcdp:latest
      restart: always
      ports:
        - "5001:5000"
      depends_on:
        - mysql_db_staging
        - mongo_db_staging

    # chatCDP services https://github.com/munishgandhi/JAI.GPT.LeaseGPT.MailGPT/tree/main/ChatCDP
    chatcdp_services_staging: 
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/chatcdp-services:latest
      restart: always
      ports:
        - "5011:5000"
      depends_on:
        - mysql_db_staging
        - mongo_db_staging

    # https://github.com/munishgandhi/etl-hub/tree/datascience_stg
    # pai_datascience_services_staging: 
    #   image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-staging/pai-datascience-services:latest
    #   restart: always
    #   ports: 
    #     - "82:80"
    #   depends_on:
    #     - mysql_db_staging
    #     - mongo_db_staging

volumes:
  mysql_data_staging:
    external: true
  mongo_data_staging:
    external: true
  redis_data_staging:
    external: true
    
networks:
  default:
    name: microservices_staging
    external: true