version: '3.4'
services:
    # MySQL Database
    # mysql_db_dev:
    #   image: mysql:8.0
    #   restart: always
    #   environment:
    #     MYSQL_ALLOW_EMPTY_PASSWORD: true
    #   ports:
    #     - "3306:3306"
    #   volumes:
    #     - /db_volumes/mysql_data_dev:/var/lib/mysql

    # MongoDB Database
    mongo_db_dev:
      image: mongo:5.0.21
      env_file:
        - /home/ubuntu/code/.env.mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - /home/ubuntu/code/db_volumes/mongo_data_dev:/data/db
  
    # Redis Database
    redis_db_dev:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --bind 0.0.0.0

    # chatCDP https://github.com/munishgandhi/chatCDP
    chatcdp_dev:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/chatcdp:latest
      env_file:
        - /home/ubuntu/code/.env.chatcdp_dev
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports:
        - "5000:5000"
      depends_on:
        - redis_db_dev

    # chatCDP services https://github.com/munishgandhi/JAI.GPT.LeaseGPT.MailGPT/tree/main/ChatCDP
    chatcdp_services_dev:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/chatcdp-services:latest
      env_file:
        - /home/ubuntu/code/.env.chatcdp_services_dev
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports:
        - "5010:5000"

    # https://github.com/munishgandhi/etl-hub/tree/datascience_dev
    pai_datascience_services_dev:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/pai-datascience-services:latest
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      volumes:
        - pai_datascience_services:/services
      ports:
        - "81:80"
        - "8888:8888"
        - "8889:8889"
        - "8890:8890"

    hayleygpt_dev:
      image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/hayleygpt:latest
      env_file:
        - /home/ubuntu/code/.env.hayleygpt_dev
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
        resources:
          limits:
            cpus: '0.40'
            memory: 3g
      ports:
        - "5005:5000"
      depends_on:
        - mongo_db_dev

    # etl_hub_dev:
    #   image: us-east1-docker.pkg.dev/gds-prototype-20190629/ml-dev/etl-hub:latest
    #   deploy:
    #     restart_policy:
    #       condition: on-failure
    #       delay: 5s
    #       max_attempts: 3
    #       window: 120s

    #     resources:
    #       limits:
    #         cpus: '0.25'
    #         memory: 350M
    #   ports:
    #     - "3000:3000"

volumes:
  pai_datascience_services:
  # mysql_data_dev:
  #   external: true
  mongo_data_dev:
    external: true
  redis_data_dev:
    external: true


networks:
  default:
    name: microservices_dev
    external: true
