name: Kubectl Deploy - Policies, Routes, Gateways

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure kubectl
        run: |
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials hyly-ml-prod --zone=us-east1
          kubectl config set-context --current --namespace=hyly-prod
 
      - name: Apply Policies
        run: |
          kubectl apply -f kubernetes/gateway-routes/policy-oneminutechatbot.yaml
          kubectl apply -f kubernetes/gateway-routes/policy-hylyimageclassification.yaml
          kubectl apply -f kubernetes/gateway-routes/policy-hayleygpt.yaml
          kubectl apply -f kubernetes/gateway-routes/policy-mailbot.yaml
          kubectl apply -f kubernetes/gateway-routes/policy-chatcdp-services.yaml
      
      - name: Apply Routes
        run: |
          kubectl apply -f kubernetes/gateway-routes/route-oneminutechatbot.yaml
          kubectl apply -f kubernetes/gateway-routes/route-hylyimageclassification.yaml
          kubectl apply -f kubernetes/gateway-routes/route-hayletgpt.yaml
          kubectl apply -f kubernetes/gateway-routes/route-mailbot.yaml
          kubectl apply -f kubernetes/gateway-routes/route-chatcdp-services.yaml

      - name: Apply Gateway
        run: |
          kubectl apply -f kubernetes/gateway-routes/gateway.yaml
    
      - name: Clean up
        run: |
          kubectl config unset users.gke_gds-prototype-20190629_us-east1_hyly-ml-prod
          kubectl config unset contexts.gke_gds-prototype-20190629_us-east1_hyly-ml-prod
          kubectl config unset clusters.gke_gds-prototype-20190629_us-east1_hyly-ml-prod